GENRES = [
    'Action',
    'Adventure',
    'Comedy',
    'Demons',
    'Drama',
    'Ecchi',
    'Fantasy',
    'Gender Bender',
    'Harem',
    'Historical',
    'Horror',
    'Josei',
    'Magic',
    'Martial Arts',
    'Mature',
    'Mecha',
    'Military',
    'Mystery',
    'One Shot',
    'Psychological',
    'Romance',
    'School Life',
    'Sci-Fi',
    'Seinen',
    'Shoujo',
    'Shoujoai',
    'Shounen',
    'Shounenai',
    'Slice of Life',
    'Smut',
    'Sports',
    'Super Power',
    'Supernatural',
    'Tragedy',
    'Vampire',
    'Yaoi',
    'Yuri',
]